git_tracker/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("tracker.urls")),
    path("user/", include("user.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

tracker/urls.py
from django.urls import path

from tracker import views

app_name = "tracker"

urlpatterns = [
    path("", views.DashboardView.as_view(), name="dashboard"),
    path("tokens/", views.TokenListView.as_view(), name="gittoken_list"),
    path("tokens/create/", views.TokenCreateView.as_view(), name="gittoken_create"),
    path("tokens/<int:pk>/edit/", views.TokenEditView.as_view(), name="gittoken_edit"),
    path("tokens/<int:pk>/delete/", views.delete_token, name="gittoken_delete"),
    path("repository/", views.RepositoryListView.as_view(), name="repository_list"),
    path(
        "repository/<int:pk>/analysis/",
        views.RepositoryStatsView.as_view(),
        name="repository_analysis",
    ),
    path(
        "repository/<int:repository_id>/commits/",
        views.CommitListView.as_view(),
        name="commit_list",
    ),
    path(
        "repository/<int:repository_id>/commits/<int:commit_id>/",
        views.CommitDetailView.as_view(),
        name="commit_detail",
    ),
    path(
        "anomalies/",
        view=views.AnomalyListView.as_view(),
        name="anomaly_list",
    ),
    path(
        "webhook/",
        view=views.webhook_listener_view,
        name="webhook_listener",
    ),
]

user/urls.py
from django.urls import path
from user import views


app_name = "user"

urlpatterns = [
    path("register/", views.RegisterView.as_view(), name="register"),
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.logout_user, name="logout"),
]

tracker/forms.py
from core.forms import BaseModelForm
from tracker import models
from django import forms


class TokenForm(BaseModelForm):
    '''
    Form to create a new token
    '''

    token = forms.CharField()

    class Meta:
        model = models.GitToken
        fields = ["service", "label", "token", "is_active"]

tracker/views.py
import json
from datetime import timedelta
from typing import Any

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Avg, Count, F, Max, Min, Sum
from django.db.models.functions import ExtractHour, TruncDay
from django.db.models.query import QuerySet
from django.http import HttpRequest, HttpResponse, QueryDict, request
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.utils import timezone
from django.utils.timezone import timedelta
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import DetailView, TemplateView
from github import Github

from core.views import BaseCreateView, BaseListView, BaseUpdateView, ListAction
from tracker import forms, models
from tracker.services.repository import RepositorySyncService

from .models import Author, Commit, Repository


class DashboardView(TemplateView):
    template_name = "dashboard.html"

    _author = None

    def get_author(self):
        if self._author is False:
            return None
        if self._author is None:
            author_username = self.request.GET.get("author")
            if not author_username:
                self._author = False
            else:
                self._author = Author.objects.filter(username=author_username).first()
                if not self._author:
                    self._author = False
                    messages.error(self.request, "Author not found")
                else:
                    messages.success(self.request, f"Showing stats for {author_username}")
        return self._author

    def get_commit_queryset(self):
        author = self.get_author()
        if author:
            return Commit.objects.filter(author=author)
        return Commit.objects.all()

    def get_repository_queryset(self):
        author = self.get_author()
        if author:
            return Repository.objects.filter(commit__author=author).distinct()
        return Repository.objects.all()

    def get_generic_stats(self):
        data = {}
        # Total Repositories
        data["total_repositories"] = self.get_repository_queryset().count()

        # Total Commits
        data["total_commits"] = self.get_commit_queryset().count()

        # Top Language
        data["top_language"] = (
            self.get_repository_queryset()
            .values("language")
            .annotate(language_count=Count("language"))
            .order_by("-language_count")
            .first()
        )

        # Average Commits per Repository
        total_commits = self.get_commit_queryset().count()
        total_repositories = self.get_repository_queryset().count()
        data["average_commits_per_repo"] = (
            total_commits / total_repositories if total_repositories else 0
        )

        # Recent Commits
        data["recent_commits"] = (
            self.get_commit_queryset().select_related("author").order_by("-date")[:10]
        )

        # Active Repositories
        last_30_days = timezone.now() - timedelta(days=30)
        data["active_repositories"] = (
            self.get_commit_queryset()
            .filter(date__gte=last_30_days)
            .values("repository__name")
            .annotate(commit_count=Count("id"))
            .order_by("-commit_count")[:5]
        )

        # Commit Frequency
        data["commit_frequency"] = (
            self.get_commit_queryset()
            .filter(date__gte=last_30_days)
            .annotate(date_day=TruncDay("date"))
            .values("date_day")
            .annotate(commit_count=Count("id"))
            .order_by("date_day")
        )

        # Churn Rate
        churn_rate = (
            self.get_commit_queryset()
            .filter(date__gte=last_30_days)
            .aggregate(
                total_additions=Sum("additions"), total_deletions=Sum("deletions")
            )
        )
        data["churn_rate"] = {
            "total_additions": churn_rate.get("total_additions", 0) or 0,
            "total_deletions": churn_rate.get("total_deletions", 0) or 0,
        }

        # Commits by Language
        data["commits_by_language"] = (
            self.get_repository_queryset()
            .values("language")
            .annotate(commit_count=Count("commit"))
            .order_by("-commit_count")
        )

        # Repository Comparison
        data["repository_comparison"] = (
            self.get_repository_queryset()
            .annotate(
                total_commits=Count("commit"),
                total_contributors=Count("commit__author", distinct=True),
                churn_rate=Sum("commit__additions") + Sum("commit__deletions"),
            )
            .values("name", "total_commits", "total_contributors", "churn_rate")
            .order_by("-total_commits")
        )

        return data

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(self.get_generic_stats())
        return context


class TokenCreateView(LoginRequiredMixin, BaseCreateView):
    '''
    A view to create a new token
    
    '''
    form_class = forms.TokenForm
    model = models.GitToken
    success_url = reverse_lazy("tracker:gittoken_list")

    def form_valid(self, form):
        # set the user to the current user
        form.instance.user = self.request.user
        return super().form_valid(form)


class TokenEditView(LoginRequiredMixin, BaseUpdateView):
    '''
    A view to edit a token
    '''
    form_class = forms.TokenForm
    model = models.GitToken
    success_url = reverse_lazy("tracker:gittoken_list")

    def get_queryset(self):
        # show only the tokens of the current user
        return self.model.objects.filter(user=self.request.user)




class TokenListView(LoginRequiredMixin, BaseListView):
    '''
    A view to list all the tokens
    '''
    model = models.GitToken
    # Override the create button label
    create_button_label = "Create Token"
    list_display = ["label", "service", "is_active"]
    # show the delete button
    can_delete = True
    # User can search by label
    searchable_fields = [
        "label",
    ]
    
    # User can order by label and is_active
    order_by_choices = [
        ("label", "Label"),
        ("is_active", "Active"),
    ]

    def get_queryset(self):
        queryset = super().get_queryset()
        # if the user does not have the permission to view all tokens, show only the tokens of the current user
        if not self.request.user.has_perm("can_view_all_git_tokens"):
            queryset = queryset.filter(user=self.request.user)
        return queryset


@login_required
def delete_token(request: HttpRequest, pk: int):
    '''
    A view to delete a token by id
    '''
    token = models.GitToken.objects.get(pk=pk)
    # if the user is the owner of the token or has the permission to delete all tokens, delete the token
    if request.user == token.user or request.user.has_perm("can_delete_all_git_tokens"):
        # add a success message
        messages.success(request, f"Token {token.label} deleted successfully.")
        token.delete()
    else:
        # if the user does not have the permission to delete the token, show an error message
        messages.error(request, "You do not have permission to delete this token")
    return redirect("tracker:gittoken_list")


class RepositoryListView(LoginRequiredMixin, BaseListView):
    '''
    A view to list all the repositories
    '''
    model = models.Repository
    # Show following fields in the list
    list_display = [
        "name",
        "owner",
        "private",
        "language",
        "default_branch",
        "last_synced_at",
    ]
    # Disable the create button
    can_create = False
    # Disable the edit button
    can_edit = False
    # User can perform the following actions
    actions = [
        #  View the commits of the repository
        ListAction(
            "Commits",
            "bi-eye",
            models.RepositoryAction.COMMITS,
            tooltip="View Commits",
        ),
        #  View the analysis of the repository
        ListAction(
            "Analysis",
            "bi-graph-up-arrow",
            models.RepositoryAction.ANALYSIS,
            tooltip="View Analysis",
        ),
    ]
    # User can search by name, owner, description and language
    searchable_fields = ["name", "owner__username", "description", "language"]
    order_by_choices = [
        ("name", "Name"),
        ("created_at", "Created At"),
        ("updated_at", "Updated At"),
        ("pushed_at", "Pushed At"),
        ("last_synced_at", "Last Synced At"),
    ]

    def get_queryset(self):
        queryset = super().get_queryset()
        #  if the user has the permission to view all repositories, show all the repositories	
        if self.request.user.has_perm("can_view_all_repositories"):
            return queryset
        return queryset.filter(users=self.request.user)


class RepositoryStatsView(DetailView):
    '''
    A view to show the statistics of a repository
    '''
    model = Repository
    template_name = "repository_stats.html"
    context_object_name = "repository"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        repository = self.object
        # Commit Frequency
        # Get the count of commits per day
        commit_frequency = (
            Commit.objects.filter(repository=repository)
            .values("date__date")
            .annotate(commit_count=Count("id"))
            .order_by("date__date")
        )
        context["commit_frequency"] = commit_frequency

		# Total Commits for the repository
        context["commit_count"] = Commit.objects.filter(repository=repository).count()

        # Top Contributors
        top_contributors = (

tracker/templates/dashboard.html
{% extends 'base.html' %} {% block head %}
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
{% endblock head %} {% block content %}
<div class="container my-5">
  <form method="GET" action="{% url 'tracker:dashboard' %}">
    <div class="input-group mb-3">
      <input
        type="text"
        name="author"
        class="form-control"
        placeholder="Search by author"
        aria-label="Search by author"
        value="{{ request.GET.author }}"
      />
      <div class="input-group-append">
        <button class="btn btn-outline-primary" type="submit">Search</button>
      </div>
    </div>
  </form>
  <div class="row mt-4">
    <!-- Total Repositories -->
    <div class="col-md-3">
      <div class="card text-center">
        <div class="card-body">
          <h5 class="card-title">Total Repositories</h5>
          <p class="card-text display-4">{{ total_repositories }}</p>
        </div>
      </div>
    </div>
    <!-- Total Commits -->
    <div class="col-md-3">
      <div class="card text-center">
        <div class="card-body">
          <h5 class="card-title">Total Commits</h5>
          <p class="card-text display-4">{{ total_commits }}</p>
        </div>
      </div>
    </div>
    <!-- Average Commits per Repository -->
    <div class="col-md-3">
      <div class="card text-center">
        <div class="card-body">
          <h5 class="card-title">Avg. Commits per Repository</h5>
          <p class="card-text display-4">
            {{ average_commits_per_repo|floatformat:2 }}
          </p>
        </div>
      </div>
    </div>

    <!-- Top Language -->
    <div class="col-md-3">
      <div class="card text-center">
        <div class="card-body">
          <h5 class="card-title">Top Language</h5>
          <p class="card-text display-4">{{ top_language.language }}</p>
        </div>
      </div>
    </div>
  </div>

  <!-- Recent Commits Table -->
  <div class="row mt-4">
    <div class="col-md-12">
      <h3>Recent Commits</h3>
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Repository</th>
            <th>Author</th>
            <th>Commit Message</th>
            <th>Date</th>
            <th>Additions</th>
            <th>Deletions</th>
          </tr>
        </thead>
        <tbody>
          {% for commit in recent_commits %}
          <tr>
            <td>{{ commit.repository.name }}</td>
            <td>{{ commit.author.username }}</td>
            <td>{{ commit.message|truncatewords:10 }}</td>
            <td>{{ commit.date }}</td>
            <td>{{ commit.additions }}</td>
            <td>{{ commit.deletions }}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>

  <!-- Charts Section -->
  <div class="row mt-4">
    <!-- Active Repositories -->
    <div class="col-md-6">
      <h3>Active Repositories</h3>
      <canvas id="activeRepositoriesChart"></canvas>
    </div>

    <!-- Commit Frequency -->
    <div class="col-md-6">
      <h3>Commit Frequency</h3>
      <canvas id="commitFrequencyChart"></canvas>
    </div>
  </div>

  <div class="row mt-4">
    <!-- Churn Rate -->

    <div class="col-md-6">
      <h3>Churn Rate</h3>
      <canvas id="churnRateChart"></canvas>
    </div>
    <!-- Commits by Language -->
    <div class="col-md-6">
      <h3>Commits by Language</h3>
      <canvas id="commitsByLanguageChart"></canvas>
    </div>
  </div>
</div>
{% endblock %} {% block core_footer %}
<script>
    // Data for Active Repositories Chart
    var activeRepositoriesCtx = document.getElementById('activeRepositoriesChart').getContext('2d');
    var activeRepositoriesChart = new Chart(activeRepositoriesCtx, {
        type: 'bar',
        data: {
            labels: [{% for repo in active_repositories %}'{{ repo.repository__name }}',{% endfor %}],
            datasets: [{
                label: 'Commits in Last 30 Days',
                data: [{% for repo in active_repositories %}{{ repo.commit_count }},{% endfor %}],
                backgroundColor: 'rgba(54, 162, 235, 0.2)',
                borderColor: 'rgba(54, 162, 235, 1)',
                borderWidth: 1
            }]
        },
        options: {
            tooltips: {
                enabled: true,
            },
            animation: {
                duration: 2000, // Animation duration
            },
            responsive: true,
            scales: {
                y: {
                    beginAtZero: true
                }
            }
        }
    });

    // Data for Commit Frequency Chart
    var commitFrequencyCtx = document.getElementById('commitFrequencyChart').getContext('2d');
    var commitFrequencyChart = new Chart(commitFrequencyCtx, {
        type: 'line',
        data: {
            labels: [{% for freq in commit_frequency %}'{{ freq.date_day|date:"Y-m-d" }}',{% endfor %}],
            datasets: [{
                label: 'Commits per Day',
                data: [{% for freq in commit_frequency %}{{ freq.commit_count }},{% endfor %}],
                backgroundColor: 'rgba(75, 192, 192, 0.2)',
                borderColor: 'rgba(75, 192, 192, 1)',
                borderWidth: 1
            }]
        },
        options: {
            responsive: true,
            tooltips: {
                enabled: true,
            },
            animation: {
                duration: 2000, // Animation duration
            },
            scales: {
                x: {
                    time: {
                        unit: 'month'
                    }
                },
                y: {
                    beginAtZero: true
                }
            }
        }
    });

    // Data for Churn Rate Chart
    var churnRateCtx = document.getElementById('churnRateChart').getContext('2d');
    var churnRateChart = new Chart(churnRateCtx, {
        type: 'pie',
        data: {
            labels: ['Additions', 'Deletions'],
            datasets: [{
                label: 'Churn Rate',
                data: [{{ churn_rate.total_additions }}, {{ churn_rate.total_deletions }}],
                backgroundColor: ['rgba(255, 99, 132, 0.2)', 'rgba(255, 206, 86, 0.2)'],
                borderColor: ['rgba(255, 99, 132, 1)', 'rgba(255, 206, 86, 1)'],
                borderWidth: 1
            }]
        },
        options: {
            tooltips: {
                enabled: true,
            },
            animation: {
                duration: 2000, // Animation duration
            },
            responsive: true
        }
    });

  // Data for Commits by Language Chart
  var commitsByLanguageCtx = document.getElementById('commitsByLanguageChart').getContext('2d');
  var commitsByLanguageChart = new Chart(commitsByLanguageCtx, {
      type: 'pie',
      data: {
          labels: [{% for lang in commits_by_language %}'{{ lang.language }}',{% endfor %}],
          datasets: [{
              label: 'Commits by Language',
              data: [{% for lang in commits_by_language %}{{ lang.commit_count }},{% endfor %}],
              backgroundColor: [
                  'rgba(255, 99, 132, 0.2)',
                  'rgba(54, 162, 235, 0.2)',
                  'rgba(255, 206, 86, 0.2)',
                  'rgba(75, 192, 192, 0.2)',
                  'rgba(153, 102, 255, 0.2)',
                  'rgba(255, 159, 64, 0.2)'
              ],
              borderColor: [
                  'rgba(255, 99, 132, 1)',
                  'rgba(54, 162, 235, 1)',
                  'rgba(255, 206, 86, 1)',
                  'rgba(75, 192, 192, 1)',
                  'rgba(153, 102, 255, 1)',
                  'rgba(255, 159, 64, 1)'
              ],
              borderWidth: 1
          }]
      },
      options: {
          tooltips: {
              enabled: true,
          },
          animation: {
              duration: 2000, // Animation duration
          },
          responsive: true
      }
  });
</script>
{% endblock core_footer %}

tracker/templates/home.html
{% extends "base.html" %}
{% block content %}
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Dashboard</h1>

      </div>
{% endblock content %}

tracker/templates/repository_stats.html
{% extends "base.html" %} {% block head %}
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<style>
  .chart-container {
    margin: 20px 0;
  }
  .card-header {
    font-size: 1.25rem;
  }
  .chart-container {
    position: relative;
    height: 400px;
    width: 100%;
  }
</style>
{% endblock head %} {% block content %}

<h1 class="my-4">{{ repository.name }} - Repository Statistics</h1>

<div class="row">
  <!-- Total Commits -->
  <div class="col-md-6">
    <div class="card text-center">
      <div class="card-body">
        <h5 class="card-title">Total Commits</h5>
        <p class="card-text display-4">{{ commit_count }}</p>
      </div>
    </div>
  </div>
  <!-- Total Contributors -->
  <div class="col-md-6">
    <div class="card text-center">
      <div class="card-body">
        <h5 class="card-title">Total Contributors</h5>
        <p class="card-text display-4">{{ contributors_count }}</p>
      </div>
    </div>
  </div>
</div>

<div class="row mt-4">
  <!-- Commit Frequency Chart -->
  <div class="col-md-6">
    <div class="card">
      <div class="card-header">Commit Frequency</div>
      <div class="card-body">
        <div class="chart-container">
          <canvas id="commitFrequencyChart"></canvas>
        </div>
      </div>
    </div>
  </div>

  <!-- Top Contributors Chart -->
  <div class="col-md-6">
    <div class="card">
      <div class="card-header">Top 3 Contributors</div>
      <div class="card-body">
        <div class="chart-container">
          <canvas id="topContributorsChart"></canvas>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="row mt-4">
  <!-- Commit Size Distribution Chart -->
  <div class="col-md-6">
    <div class="card">
      <div class="card-header">Contributors Distribution</div>
      <div class="card-body">
        <div class="chart-container">
          <canvas id="contributorsDistributionChart"></canvas>
        </div>
      </div>
    </div>
  </div>

  <!-- Commit Time Distribution Chart -->
  <div class="col-md-6">
    <div class="card">
      <div class="card-header">Commit Time Distribution</div>
      <div class="card-body">
        <div class="chart-container">
          <canvas id="commitTimeDistributionChart"></canvas>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="row mt-4">
  <!-- Churn Rate Chart -->
  <div class="col-md-12">
    <div class="card">
      <div class="card-header">Churn Rate</div>
      <div class="card-body">
        <div class="chart-container">
          <canvas id="churnRateChart"></canvas>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %} {% block core_footer %}
<script>
  // Commit Frequency Chart
  const commitFrequencyCtx = document.getElementById('commitFrequencyChart').getContext('2d');
  new Chart(commitFrequencyCtx, {
      type: 'line',
      data: {
          labels: [{% for day in commit_frequency %}'{{ day.date__date }}',{% endfor %}],
          datasets: [{
              label: 'Commits per Day',
              data: [{% for day in commit_frequency %}{{ day.commit_count }},{% endfor %}],
              borderColor: 'rgba(75, 192, 192, 1)',
              backgroundColor: 'rgba(75, 192, 192, 0.2)',
              borderWidth: 2
          }]
      },
      options: {
          responsive: true,
          scales: {
              x: {
                  title: { display: true, text: 'Date' }
              },
              y: {
                  title: { display: true, text: 'Number of Commits' }
              }
          }
      }
  });

  // Top Contributors Chart
  const topContributorsCtx = document.getElementById('topContributorsChart').getContext('2d');
  new Chart(topContributorsCtx, {
      type: 'bar',
      data: {
          labels: [{% for contributor in top_contributors|slice:"3" %}'{{ contributor.author__username }}',{% endfor %}],
          datasets: [{
              label: 'Commits',
              data: [{% for contributor in top_contributors %}{{ contributor.commit_count }},{% endfor %}],
              backgroundColor: 'rgba(54, 162, 235, 0.2)',
              borderColor: 'rgba(54, 162, 235, 1)',
              borderWidth: 2
          }]
      },
      options: {
          responsive: true,
          scales: {
              x: {
                  title: { display: true, text: 'Contributor' }
              },
              y: {
                  title: { display: true, text: 'Number of Commits' }
              }
          }
      }
  });

  // Contributors Distribution Chart
  const contributorsDistributionCtx = document.getElementById('contributorsDistributionChart').getContext('2d');
  new Chart(contributorsDistributionCtx, {
      type: 'doughnut',
      data: {
          labels: [{% for contributor in top_contributors %}'{{ contributor.author__username }}',{% endfor %}],
          datasets: [{
              label: 'Commit Count',
              data: [{% for contributor in top_contributors %}{{ contributor.commit_count }},{% endfor %}],
              borderWidth: 2
          }]
      },
      options: {
          responsive: true
      }
  });

  // Churn Rate Chart
  const churnRateCtx = document.getElementById('churnRateChart').getContext('2d');
  new Chart(churnRateCtx, {
      type: 'bar',
      data: {
          labels: ['Total Lines Changed'],
          datasets: [{
              label: 'Churn Rate',
              data: [{{ churn_rate }}],
              backgroundColor: 'rgba(255, 159, 64, 0.2)',
              borderColor: 'rgba(255, 159, 64, 1)',
              borderWidth: 2
          }]
      },
      options: {
          responsive: true,
          scales: {
              x: {
                  title: { display: true, text: 'Metric' }
              },
              y: {
                  title: { display: true, text: 'Lines Changed' }
              }
          }
      }
  });

  // Commit Time Distribution Chart
  const commitTimeDistributionCtx = document.getElementById('commitTimeDistributionChart').getContext('2d');
  new Chart(commitTimeDistributionCtx, {
      type: 'bar',
      data: {
          labels: [{% for hour in time_distribution %}'{{ hour.hour }}:00',{% endfor %}],
          datasets: [{
              label: 'Commits per Hour',
              data: [{% for hour in time_distribution %}{{ hour.commit_count }},{% endfor %}],
              backgroundColor: 'rgba(153, 102, 255, 0.2)',
              borderColor: 'rgba(153, 102, 255, 1)',
              borderWidth: 2
          }]
      },
      options: {
          responsive: true,
          scales: {
              x: {
                  title: { display: true, text: 'Hour of Day' }
              },
              y: {
                  title: { display: true, text: 'Number of Commits' }
              }
          }
      }
  });
</script>
{% endblock core_footer %}

tracker/templates/token_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">{% if object %}Update{% else %}Create{% endif %} Access Token</h1>
    </div>
    {% crispy form form.helper %}

    <form method="POST">
      {% csrf_token %}
        <div class="row mb-3">
          <label for="token" class="col-sm-2 col-form-label">Token</label>
          <div class="col-sm-10">
            <input 
            type="text" 
            class="form-control {% if form.token.errors %}is-invalid{% endif %}" 
            id="token" 
            name="token" 
            placeholder="Enter access token"
            {% if form.token.value %}
            value="{{ form.token.value }}"
            {% endif %}
            />
            {% for error in form.token.errors %}
            <div class="invalid-feedback">{{ error }}</div>
          {% endfor %}
          </div>
        </div>
        <div class="row mb-3">
          <label for="service" class="col-sm-2 col-form-label">Service</label>
          <div class="col-sm-10">
            <select id="service" name="service" class="form-select {% if form.service.errors %}is-invalid{% endif %}">
                {% for key, value in form.service.field.choices %}
                    <option value="{{key}}"  {% if form.service.value == key %}selected{% endif %}>
                        {% if not key %}
                        Select Git Service
                        {% else %}
                        {{value}}
                        {% endif %}
                    </option>
                {% endfor %}
              </select>
              {% for error in form.service.errors %}
                <div class="invalid-feedback">{{ error }}</div>
              {% endfor %}
          </div>

        </div>

        <button type="submit" class="btn btn-primary">{% if object %}Update{% else %}Create{% endif %} Token</button>
      </form>
{% endblock content %}

tracker/templates/token_list.html
{% extends "base.html" %}
{% block content %}
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Access Tokens</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
            <div class="btn-group me-2">
                <a href="{% url "tracker:gittoken_create" %}" class="btn btn-sm btn-outline-primary">Create Token</a>
            </div>
        </div>
    </div>
    <div class="table-responsive mt-3">
        <table class="table table-bordered">
            <thead>
              <tr>
                <th scope="col">Token</th>
                <th scope="col">Service</th>
                <th scope="col">Action</th>
              </tr>
            </thead>
            <tbody>
            {% for token in object_list %}
              <tr>
                <td>{{ token.token }}</td>
                <td>{{ token.service }}</td>
                <td>
                    <a class="text-primary" href="{% url "tracker:gittoken_edit" token.pk %}" role="button">
                        <i class="bi bi-pencil-square"></i>
                    </a>
                </td>
              </tr>
            {% endfor %}            
            </tbody>
          </table>
    </div>
{% endblock content %}